export type { Diagnostic, DiagnosticSeverity } from './diagnostics/Diagnostic'
export type {
  ConnectorElement,
  ElementSource,
  Fill,
  FillBackground,
  ImageBackground,
  ImageCrop,
  ImageElement,
  ImageFill,
  LineEndStyle,
  LineStyle,
  NoFill,
  Paragraph,
  Presentation,
  PresentationMetadata,
  PresentationTheme,
  PresetShapeGeometry,
  ShapeElement,
  ShapeGeometry,
  Slide,
  SlideBackground,
  SlideElement,
  SlideLayout,
  SlideMaster,
  SolidFill,
  TextBody,
  TextElement,
  TextRun,
  TextSpacing,
  TextStyle,
  ThemeColorScheme,
  ThemeFontScheme,
  Transform,
  UnknownElement,
} from './model/Presentation'
export type { Relationship, ResolvedRelationship } from './package/Relationship'
export {
  canvasLineDash,
  orderedVisibleElements,
  solidFillColor,
  svgFill,
  svgFillOpacity,
  svgMarkerEnd,
  svgMarkerStart,
  svgStrokeDasharray,
  svgStrokeOpacity,
} from './renderer/rendererUtils'
export { parsePptx, type ParsePptxResult } from './parser/parsePptx'
export { PptxPackage } from './package/PptxPackage'
